### ISSUE TITLE
Funktionalität der Hauptseite verbessern

### ISSUE THREAD

**Issue by MiriHa** [MiriHa/InfovisGroup15#15]
Slider Function verbessern (Miriam)
Daten schöner einbinden 
Bubbles verbessern (Anna)
Balkendiagramm (Klaus)

**Comment by tg4nd4lf** [comment]
@linked to:

feature/6-verknpfung-von-slider-und-bubbles

**Comment by tg4nd4lf** [comment]
Moved to Milestone V
