### ISSUE TITLE
Seitenlogik: Verknüpfung von Slider und Bubbles and Diagramms

### ISSUE THREAD

**Issue by MiriHa** [MiriHa/InfovisGroup15#6]

**Comment by tg4nd4lf** [comment]
- divide the "bubbleContainer" in 2 seperate container (index.html) for "slider" & for "bubbles"

- render "bubbles" with specific .json depending on slider position

**Comment by tg4nd4lf** [comment]
Rebased this old branch, because it is an active issue.
Next steps:

- continue in adding the logic to call diagrams & bubbles etc.

**Comment by tg4nd4lf** [comment]
DONE:
- Refractored lineDiagram so the old one gets removed before adding a new one to svg
- Added line diagram
- first tryout to call function "visualizeLineDiagram" from "bubbles.js"


TODO:
- Refractor functions to load from .csv or .json files
- Refractor "visualizeLineDiagram" to show 2 lines (analog + digital)
- Connect slider to Bubbles (Hardcoded or with files)

**Comment by tg4nd4lf** [comment]
DONE:

- Refractored lineDiagram so the old one gets removed before adding a new one to svg
- Added line diagram
- first tryout to call function "visualizeLineDiagram" from "bubbles.js"
- Refractor functions to load from .csv

TODO:

- Refractor "visualizeLineDiagram" to show 2 lines (analog + digital)
- Connect slider to Bubbles (Hardcoded or with files)
